spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:dcbapp
    username: sa
    password: password
    driverClassName: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher