CREATE TABLE IF NOT EXISTS `BOOKINGENTITY`(
    `id`          INTEGER PRIMARY KEY,
    `bookingType`  VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS `BOOKINGENTITY`(
    `id`          INTEGER PRIMARY KEY,
    `bookingType`  VARCHAR(30) NOT NULL
);